# Generated by Django 4.1.3 on 2023-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address_nh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
