# Generated by Django 4.1.3 on 2023-05-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
