# Generated by Django 4.1.3 on 2023-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_orderplaced_payment_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
