# Generated by Django 4.1.3 on 2023-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_orderplaced_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
