# Generated by Django 4.1.3 on 2023-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
