# Generated by Django 4.2.1 on 2023-05-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merchants_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchants',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='merchants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.merchants'),
        ),
    ]
