# Generated by Django 4.2.1 on 2023-05-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_remove_merchants_product_product_merchants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rider',
            name='xe',
            field=models.CharField(choices=[('CarNumber', 'CarNumber'), ('Car', 'Car'), ('motorbike', 'motorbike')], default='CarNumber', max_length=50),
        ),
    ]
