# Generated by Django 4.2.1 on 2023-05-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ridersavedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiderSavedOrder',
        ),
    ]
