# Generated by Django 4.2.1 on 2023-05-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_ridersavedorders_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='address_rd',
        ),
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ridersavedorders',
            name='xe',
        ),
    ]
